apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rails-app
  template:
    metadata:
      labels:
        app: rails-app
    spec:
      containers:
        - name: rails-app
          image: #your-docker-image-for-rails-app:latest
          ports:
            - containerPort: 3000
          env:
            - name: RAILS_ENV
              value: production
            - name: POSTGRES_DB
              value: postgres
            - name: PG_HOST
              value: localhost
            - name: POSTGRES_USER
              value: root
            - name: POSTGRES_PASSWORD
              value: quorumUS@321
            - name: ELASTICSEARCH_URL
              value: http://elasticsearch:9200
            - name: RABBITMQ_URL
              value: amqp://guest:guest@rabbitmq:5672
            - name: RABBITMQ_EXCHANGE
              value: my_exchange
            - name: RABBITMQ_QUEUE
              value: my_queue
            - name: REDIS_URL
              value: redis://redis:6379/0

---
apiVersion: v1
kind: Service
metadata:
  name: rails-app-service
spec:
  selector:
    app: rails-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort